import {
    FaDotCircle,
    FaSkullCrossbones,
    FaHatWizard,
    FaSeedling,
    FaMountain,
    FaIcicles,
    FaFire,
    FaFistRaised,
    FaTint,
    FaGem,
    FaBolt,
    FaGhost,
    FaBug,
    FaDragon,
    FaDove,
    FaMagic,
    FaCircle,
    FaDumbbell
} from "react-icons/fa";

/* ข้อมูลสี แต่ละประเภทของโปเกม่อน */
export const typeColors = {
    normal: "#A8A878",
    poison: "#A040A0",
    psychic: "#F85888",
    grass: "#77c360",
    ground: "#E0C068",
    ice: "#98D8D8",
    fire: "#F08030",
    rock: "#B8A038",
    dragon: "#7038F8",
    water: "#6890F0",
    bug: "#A8B820",
    dark: "#705848",
    fighting: "#C03028",
    ghost: "#705898",
    steel: "#B8B8D0",
    electric: "#F8D030",
    flying: "#A890F0",
    fairy: "#EE99AC",
};

/* ข้อมูลIcons แต่ละประเภทของโปเกม่อน */
export const typeIcon = {
    normal: <FaDotCircle />,
    poison: <FaSkullCrossbones />,
    psychic: <FaHatWizard />,
    grass: <FaSeedling />,
    ground: <FaMountain />,
    ice: <FaIcicles />,
    fire: <FaFire />,
    rock: <FaGem />,
    dragon: <FaDragon />,
    water: <FaTint />,
    bug: <FaBug />,
    dark: <FaCircle />,
    fighting: <FaFistRaised />,
    ghost: <FaGhost />,
    steel: <FaDumbbell />,
    electric: <FaBolt />,
    flying: <FaDove />,
    fairy: <FaMagic />,
};

